# AUTO-GENERATED by scripts/build_submission.py — do not hand-edit.
# Source of truth is src/kaggriculture/. Edit there, then re-run:
#     python scripts/build_submission.py
from __future__ import annotations

# -------- from mechanics.py --------
"""
mechanics.py — Verified Kaggriculture engine constants and reference data.

Every value here is confirmed against `kaggle_environments==1.32.7` source
and its bundled AGENTS.md / README.md, per this project's own verified-
mechanics report — not reconstructed from any prior agent file's comments.
Where a prior file's comments claimed a "confirmed" fact but cited a
PROJECT_STATE.md that doesn't exist anywhere in this environment, that
claim is deliberately NOT included here.
"""

from dataclasses import dataclass
from enum import Enum

# ---------------------------------------------------------------------------
# Episode / board structure
# ---------------------------------------------------------------------------

TURNS_PER_DAY: int = 24
TOTAL_DAYS: int = 30
TOTAL_STEPS: int = TURNS_PER_DAY * TOTAL_DAYS  # 720, confirmed exact

BOARD_SIZE: int = 10  # four 5x5 quadrants
STARTING_MONEY: int = 3_000
QUADRANT_COSTS: tuple[int, ...] = (1_000, 2_000, 4_000)  # cost of the 2nd/3rd/4th quadrant; NW starts unlocked

# NOT resolved: how many quadrants a strong agent should buy. The prior
# main.py/new_agent_wip.py comments disagreed with each other (one claims
# real top players stopped at exactly 3, a different comment justifies a
# coordinate-ascent-found cap of 2). Real 9-game data shows all 9 winners
# reached a 3rd quadrant by day 9-11 -- a point in favor of 3, but not a
# direct A/B test against 2. Keep this tunable, resolve via real self-play:
MAX_QUADRANTS_CANDIDATES: tuple[int, ...] = (2, 3)

# ---------------------------------------------------------------------------
# Action vocabulary — every other string is a confirmed silent no-op
# ---------------------------------------------------------------------------


class Action(str, Enum):
    NORTH = "NORTH"
    SOUTH = "SOUTH"
    EAST = "EAST"
    WEST = "WEST"
    PASS = "PASS"
    PICKUP = "PICKUP"
    DROP = "DROP"
    PLACE = "PLACE"
    PLANT = "PLANT"
    WATER = "WATER"
    HARVEST = "HARVEST"
    FERTILIZE = "FERTILIZE"
    FEED = "FEED"
    COLLECT_FERTILIZER = "COLLECT_FERTILIZER"
    CARE = "CARE"
    BUILD_COOP = "BUILD_COOP"
    BUILD_PASTURE = "BUILD_PASTURE"
    DIG = "DIG"  # confirmed weed-removal action
    BUY_SEED = "BUY_SEED"
    BUY_PRODUCT = "BUY_PRODUCT"  # wheat / fertilizer only
    BUY_ANIMAL = "BUY_ANIMAL"
    SELL = "SELL"
    HIRE = "HIRE"
    BUY_LAND = "BUY_LAND"
    # NOTE: SELL_ANIMAL, REMOVE_WEED, and ["PICKUP", "WEED"] are confirmed
    # to NOT exist. Any code path that still emits them is a silent no-op.


MAX_MARKET_ORDERS_PER_TURN: int = 10  # extras silently dropped

# ---------------------------------------------------------------------------
# Crop yield / decay — the single most important newly-confirmed mechanic.
# No prior agent version modeled this correctly; the shipped fix (bumping
# HARVEST's tier ahead of WATER) never used max_lifespan_step directly.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CropProfile:
    first_yield_day: int
    max_yield_day: int | None  # None for "ongoing" crops (tomato/strawberry)
    max_yield: int  # fertilized max, per confirmed table
    max_yield_unfertilized: int | None = None
    ongoing_interval_days: int | None = None  # tomato=1, strawberry=2
    ongoing_productions: int | None = None  # both ongoing crops: 4


CROPS: dict[str, CropProfile] = {
    "WHEAT": CropProfile(first_yield_day=2, max_yield_day=4, max_yield=6, max_yield_unfertilized=4),
    "CARROT": CropProfile(first_yield_day=2, max_yield_day=3, max_yield=4, max_yield_unfertilized=3),
    "MELON": CropProfile(first_yield_day=10, max_yield_day=12, max_yield=6),
    "TOMATO": CropProfile(first_yield_day=8, max_yield_day=None, max_yield=4, ongoing_interval_days=1, ongoing_productions=4),
    "STRAWBERRY": CropProfile(first_yield_day=10, max_yield_day=None, max_yield=4, ongoing_interval_days=2, ongoing_productions=4),
}


def is_decaying(max_lifespan_step: int | None, current_step: int) -> bool:
    """True once a tile has passed max_lifespan_step. Reads the field
    directly rather than inferring decay from yield_units or age — exactly
    the mistake every prior agent version made."""
    if max_lifespan_step is None:
        return False
    return current_step > max_lifespan_step


def decay_urgency(max_lifespan_step: int | None, current_step: int) -> float:
    """Higher = more urgent to harvest NOW. Once decaying, yield_units drops
    by 1 every other turn until the tile becomes a weed — so every 2 turns
    of delay past max_lifespan_step is a full unit of yield, permanently
    lost."""
    if max_lifespan_step is None:
        return 0.0
    turns_past_decay = current_step - max_lifespan_step
    if turns_past_decay <= 0:
        return 0.0
    return turns_past_decay / 2.0


# ---------------------------------------------------------------------------
# Watering / feeding — miss 2 consecutive end-of-day refreshes = unrecoverable
# ---------------------------------------------------------------------------

MAX_CONSECUTIVE_UNWATERED: int = 2  # on the 2nd miss, tile becomes a weed
MAX_CONSECUTIVE_UNFED: int = 2  # on the 2nd miss, animal escapes
FRESH_PLANT_STARTING_UNWATERED: int = 1  # no grace period
FRESH_ANIMAL_STARTING_UNFED: int = 0  # one free day

# ---------------------------------------------------------------------------
# Shed
# ---------------------------------------------------------------------------

SHED_CAPACITY: int = 100  # flat cap; seeds live in a separate, uncapped slot
# Overflow at end-of-day drop is discarded, not held anywhere.

# ---------------------------------------------------------------------------
# Hiring
# ---------------------------------------------------------------------------


def hire_cost(hires_today: int) -> int:
    """Fibonacci cost, resets each day: 1, 1, 2, 3, 5, 8, 13, 21, ..."""
    a, b = 1, 1
    for _ in range(hires_today):
        a, b = b, a + b
    return a


# ---------------------------------------------------------------------------
# Town / shops — real per-shop demand table. Every prior agent used only a
# shop-count proxy; this table lets selling logic anticipate actual drains.
# ---------------------------------------------------------------------------

SHOPS: dict[str, tuple[str, ...]] = {
    "BAKERY": ("EGG", "WHEAT"),
    "PIZZA_SHOP": ("MILK", "TOMATO", "WHEAT"),
    "BRUNCH_SPOT": ("EGG", "WHEAT", "STRAWBERRY"),
    "YARN_STORE": ("WOOL",),  # single-product: 2x consumption
    "ICE_CREAM_SHOP": ("STRAWBERRY", "MILK", "WHEAT"),
    "PET_CAFE": ("CARROT",),  # single-product: 2x consumption
    "SMOOTHIE_SHOP": ("STRAWBERRY", "MILK"),
    "FARMERS_MARKET": ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY"),
}
SINGLE_PRODUCT_SHOPS: frozenset[str] = frozenset({"YARN_STORE", "PET_CAFE"})

TOWN_SHOP_SELL_INTERVAL: int = 4  # turns; each unlocked shop instance drains 1 of every listed product
TOWN_CENTER_SELL_INTERVAL: int = 24  # turns; drains 1 of every non-fertilizer product, flat rate
SHOP_UNLOCK_INTERVAL_DAYS: int = 3  # a new shop is drawn (with replacement) every 3 days
MAX_SHOP_INSTANCES: int = 8


def per_turn_shop_demand(unlocked_shops: list[str]) -> dict[str, float]:
    """Expected per-turn drain for each product from town/shop mechanics,
    given the current list of unlocked shop instances (duplicates allowed)."""
    demand: dict[str, float] = {}
    for shop in unlocked_shops:
        products = SHOPS.get(shop, ())
        weight = 2.0 if shop in SINGLE_PRODUCT_SHOPS else 1.0
        for product in products:
            demand[product] = demand.get(product, 0.0) + weight / TOWN_SHOP_SELL_INTERVAL
    return demand


# ---------------------------------------------------------------------------
# Market pricing — shape differs per resource. Exact amp/curve constants
# weren't captured in the source report, so this is directional only:
# melon/wool ("sq"): crash hard on gluts, sell early and steadily.
# wheat ("log"): forgiving on gluts, safe to sell in bulk.
# carrot/tomato/egg ("hinge"): stays near base until a scarcity knee, then
#   rises fast — avoid dumping inventory that resets this knee.
# ---------------------------------------------------------------------------

MARKET_STARTING_INVENTORY: int = 10_000  # I0, every product

# -------- from state.py --------
"""
state.py — Clean, typed representations of parsed Kaggriculture observations.

Only fields explicitly confirmed (via installed kaggle_environments source,
its AGENTS.md/README.md, or this project's verified-mechanics report) are
treated as certain here. The exact top-level container shape for tiles and
units was NOT independently confirmed in this project's source material —
that gap lives in agent.py::parse_observation(), isolated from everything
in this file, which stays correct regardless of how that gets resolved.
"""

from dataclasses import dataclass, field


@dataclass
class TileState:
    x: int
    y: int
    crop: str | None = None
    yield_units: int = 0
    max_lifespan_step: int | None = None  # confirmed field; drives decay
    consecutive_unwatered: int = 0
    fertilized: bool = False
    structure: str | None = None  # "COOP" | "PASTURE" | None
    animal: str | None = None
    consecutive_unfed: int = 0
    is_weed: bool = False
    quadrant: int = 0  # which of the 4 quadrants this tile is in
    locked: bool = False  # unbought quadrant — passable, actions no-op here


@dataclass
class UnitState:
    unit_id: str
    x: int
    y: int
    carrying: dict[str, int] = field(default_factory=dict)


@dataclass
class FarmState:
    step: int
    day: int
    money: int
    shed: dict[str, int]  # obs["private"]["shed"] — confirmed correct
    seeds: dict[str, int]  # separate, uncapped slot
    market_prices: dict[str, float]  # obs["market"]["prices"] — confirmed correct
    market_inventory: dict[str, int]  # obs["market"]["inventory"] — confirmed correct
    unlocked_shops: list[str]  # obs["town"]["unlocked_shops"] — list, duplicates possible
    unlocked_quadrants: int
    hires_today: int
    tiles: list[TileState]
    units: list[UnitState]


def size_keeper_pool(n_units: int, n_animals_active: int) -> int:
    """
    Independently verified stable-pool-sizing formula. Sizing off herd size
    rather than raw unit count keeps pool membership stable across a
    same-day hire: a new hire changes n_units immediately, but
    n_animals_active only changes when an animal is actually bought and
    placed — so the keeper set doesn't reshuffle just because headcount
    went up. Confirmed to fix a pool-flip bug where a unit got yanked off
    wheat-watering to cow-feeding purely because a hire happened, same
    task backlog, only headcount changed.
    """
    return max(1, min(3, n_units - 2, 1 + n_animals_active // 3))

# -------- from strategy.py --------
"""
strategy.py — Task generation and prioritization.

The one thing every prior agent version got wrong or left unfinished:
HARVEST priority needs to be driven directly by max_lifespan_step (decay),
not a fixed tier number reasoned about in the abstract. This module
computes a continuous urgency score per task instead of a fixed tier, so
decay pressure and routine upkeep can be weighed against each other rather
than lexicographically ordered.

Known gap, intentionally not solved here: crop selection for empty,
plantable tiles is a placeholder (always WHEAT — see generate_tasks). A
real heuristic (season timing, market price, quadrant mix) is the next
piece of strategy to build, not included in this pass.
"""

from dataclasses import dataclass



@dataclass
class Task:
    kind: str
    tile: TileState
    urgency: float  # higher = more urgent; used to sort, not a fixed tier


# Base urgency per task kind, before decay/backlog adjustments. Tunable —
# starting points informed by this project's process history (CARE and
# weed-DIG were previously under-prioritized and had to be bumped after
# observed failures), not re-derived from scratch here.
BASE_URGENCY: dict[str, float] = {
    "FEED_CRITICAL": 100.0,  # one more miss loses the animal
    "WATER_CRITICAL": 95.0,  # one more miss turns the tile into a weed
    "HARVEST_DECAYING": 90.0,  # scales up further the longer it's ignored
    "PLACE": 80.0,
    "FEED_ROUTINE": 60.0,
    "WATER_ROUTINE": 55.0,
    "HARVEST_FRESH": 50.0,  # ripe but not yet decaying — still worth prioritizing over routine upkeep
    "CARE": 45.0,
    "DIG": 40.0,  # weed removal — DIG is confirmed real; ["PICKUP","WEED"] is not
    "BUILD": 35.0,
    "PLANT": 30.0,
    "FERTILIZE": 20.0,
    "COLLECT_FERTILIZER": 10.0,
}


def harvest_urgency(tile: TileState, current_step: int) -> float:
    """
    Decay-aware HARVEST urgency. Every prior fix (tier 1 -> 5 -> 4) reasoned
    about this qualitatively ("land isn't earning"); this computes it
    directly from the confirmed mechanic: once max_lifespan_step passes,
    yield_units drops by 1 every other turn until the tile becomes a weed.
    """
    urgency = decay_urgency(tile.max_lifespan_step, current_step)
    if urgency > 0:
        return BASE_URGENCY["HARVEST_DECAYING"] + min(urgency, 10.0) * max(tile.yield_units, 1)
    if tile.yield_units > 0:
        return BASE_URGENCY["HARVEST_FRESH"]
    return 0.0


def generate_tasks(farm: FarmState) -> list[Task]:
    tasks: list[Task] = []

    for tile in farm.tiles:
        if tile.locked:
            continue  # every tile action no-ops on an unbought quadrant

        if tile.is_weed:
            tasks.append(Task("DIG", tile, BASE_URGENCY["DIG"]))
            continue

        if tile.yield_units > 0 or tile.max_lifespan_step is not None:
            u = harvest_urgency(tile, farm.step)
            if u > 0:
                tasks.append(Task("HARVEST", tile, u))

        if tile.crop is not None:
            grace_left = MAX_CONSECUTIVE_UNWATERED - tile.consecutive_unwatered
            key = "WATER_CRITICAL" if grace_left <= 1 else "WATER_ROUTINE"
            tasks.append(Task("WATER", tile, BASE_URGENCY[key]))
            if not tile.fertilized:
                tasks.append(Task("FERTILIZE", tile, BASE_URGENCY["FERTILIZE"]))

        if tile.animal is not None:
            grace_left = MAX_CONSECUTIVE_UNFED - tile.consecutive_unfed
            key = "FEED_CRITICAL" if grace_left <= 1 else "FEED_ROUTINE"
            tasks.append(Task("FEED", tile, BASE_URGENCY[key]))
            tasks.append(Task("CARE", tile, BASE_URGENCY["CARE"]))

        if tile.structure is not None and tile.animal is None:
            tasks.append(Task("PLACE", tile, BASE_URGENCY["PLACE"]))

        if (
            tile.crop is None
            and tile.structure is None
            and tile.animal is None
            and tile.yield_units == 0
        ):
            # Empty, plantable tile. Crop choice is a placeholder (always
            # WHEAT) — see module docstring.
            tasks.append(Task("PLANT", tile, BASE_URGENCY["PLANT"]))

    tasks.sort(key=lambda t: t.urgency, reverse=True)
    return tasks


def shop_aware_sell_plan(farm: FarmState, max_orders: int = 8) -> list[tuple[str, int]]:
    """
    Sell targeting informed by the real per-shop demand table instead of a
    shop-count proxy. Prioritizes selling products with the lowest expected
    town/shop demand relative to shed quantity first — those are least
    likely to get picked up by passive town drains, and most likely to
    approach SHED_CAPACITY and be destroyed unsold at end-of-day.
    """
    demand = per_turn_shop_demand(farm.unlocked_shops)
    plan: list[tuple[str, int]] = []
    for item, qty in farm.shed.items():
        if qty <= 0:
            continue
        expected_drain = demand.get(item, 0.0)
        pressure = qty / SHED_CAPACITY - expected_drain
        if pressure > 0.3:
            plan.append((item, qty))
    plan.sort(key=lambda p: p[1], reverse=True)
    return plan[:max_orders]

# -------- from agent.py --------
"""
agent.py — Kaggriculture submission entrypoint.

CONFIRMED (verified against installed kaggle_environments==1.32.7 and its
AGENTS.md/README.md, per this project's verified-mechanics report): every
field name used in parse_observation() below under obs["private"],
obs["market"], and obs["town"], plus max_lifespan_step and the
consecutive_unwatered/consecutive_unfed tile fields.

NOT YET CONFIRMED — flagged inline with `# VERIFY:` — exactly two things:
  1. The top-level container shape for iterating tiles and units.
  2. The expected return format for actions.
Both are isolated to this file. state.py, strategy.py, and mechanics.py
don't need to change once you confirm them — run test_harness.py, inspect
the dumped sample_observation.json, and fix the two spots below.

Also not yet implemented: unit-to-tile movement/pathing. Tasks are
assigned to units directly with no travel step modeled — the next real
piece of work once the schema is confirmed, not guessed at here.
"""

import logging
from typing import Any


logger = logging.getLogger("kaggriculture_agent")
logging.basicConfig(level=logging.WARNING)  # flip to INFO/DEBUG for local runs; keep quiet in competition


def parse_observation(obs: dict[str, Any], config: dict[str, Any]) -> FarmState:
    private = obs["private"]
    market = obs["market"]
    town = obs["town"]

    # VERIFY: adjust these two lines to the real top-level obs shape once
    # you've inspected sample_observation.json from test_harness.py.
    raw_tiles = obs.get("tiles", [])
    raw_units = obs.get("units", [])

    tiles = [
        TileState(
            x=t["x"],
            y=t["y"],
            crop=t.get("crop"),
            yield_units=t.get("yield_units", 0),
            max_lifespan_step=t.get("max_lifespan_step"),
            consecutive_unwatered=t.get("consecutive_unwatered", 0),
            fertilized=t.get("fertilized", False),
            structure=t.get("structure"),
            animal=t.get("animal"),
            consecutive_unfed=t.get("consecutive_unfed", 0),
            is_weed=t.get("is_weed", False),
            quadrant=t.get("quadrant", 0),
            locked=t.get("locked", False),
        )
        for t in raw_tiles
    ]
    units = [
        UnitState(unit_id=u["id"], x=u["x"], y=u["y"], carrying=u.get("carrying", {}))
        for u in raw_units
    ]

    return FarmState(
        step=obs.get("step", 0),
        day=obs.get("day", obs.get("step", 0) // 24),  # VERIFY: obs may expose "day" directly
        money=private.get("money", 0),
        shed=private.get("shed", {}),
        seeds=private.get("seeds", {}),
        market_prices=market.get("prices", {}),
        market_inventory=market.get("inventory", {}),
        unlocked_shops=town.get("unlocked_shops", []),
        unlocked_quadrants=private.get("unlocked_quadrants", 1),
        hires_today=private.get("hires_today", 0),
        tiles=tiles,
        units=units,
    )


def agent(obs: dict[str, Any], config: dict[str, Any]) -> dict[str, list[Any]]:
    """
    VERIFY: the return shape. Assumed here — a dict mapping unit_id to an
    action list, e.g. {"unit_3": ["PICKUP", "WHEAT", 5]} — is the common
    convention for multi-unit Kaggle simulation competitions, but this
    project's source material never pinned down the exact expected format.
    Confirm against AGENTS.md/README.md or a real successful env.run()
    before trusting this in a real submission.
    """
    try:
        farm = parse_observation(obs, config)
    except Exception:
        logger.exception("parse_observation failed; returning no actions as a safe fallback")
        return {}

    n_animals_active = sum(1 for t in farm.tiles if t.animal is not None)
    n_keepers = size_keeper_pool(len(farm.units), n_animals_active)
    keepers = farm.units[:n_keepers]  # first-k, stable across same-day hires
    crop_crew = farm.units[n_keepers:]

    tasks = generate_tasks(farm)
    sell_plan = shop_aware_sell_plan(farm)

    # First-pass allocator, not a solved scheduler: no movement/pathing
    # between a unit and its assigned tile is modeled yet.
    animal_tasks = [t for t in tasks if t.kind in ("FEED", "CARE", "PLACE", "BUILD")]
    crop_tasks = [t for t in tasks if t.kind in ("HARVEST", "WATER", "FERTILIZE", "PLANT", "DIG", "COLLECT_FERTILIZER")]

    actions: dict[str, list[Any]] = {}
    for unit, task in zip(keepers, animal_tasks + crop_tasks):
        actions[unit.unit_id] = [task.kind]
    for unit, task in zip(crop_crew, crop_tasks + animal_tasks):
        actions.setdefault(unit.unit_id, [task.kind])

    if sell_plan:
        # VERIFY: who/what submits a market order. ["SELL", item, n] is the
        # confirmed action shape; attaching it under "_market" here is a
        # placeholder, not a confirmed submission convention.
        market_orders: list[Any] = []
        for item, qty in sell_plan[: len(sell_plan)]:
            market_orders.extend(["SELL", item, qty])
        if market_orders:
            actions["_market"] = market_orders

    return actions

