# AUTO-GENERATED by scripts/build_submission.py — do not hand-edit.
# Source of truth is src/kaggriculture/. Edit there, then re-run:
#     python scripts/build_submission.py
from __future__ import annotations

# -------- from mechanics.py --------
"""
mechanics.py — Verified Kaggriculture engine constants and reference data.

Every value here is confirmed against `kaggle_environments==1.32.7` source
and its bundled AGENTS.md / README.md, per this project's own verified-
mechanics report — not reconstructed from any prior agent file's comments.
Where a prior file's comments claimed a "confirmed" fact but cited a
PROJECT_STATE.md that doesn't exist anywhere in this environment, that
claim is deliberately NOT included here.
"""

from dataclasses import dataclass
from enum import Enum

# ---------------------------------------------------------------------------
# Episode / board structure
# ---------------------------------------------------------------------------

TURNS_PER_DAY: int = 24
TOTAL_DAYS: int = 30
TOTAL_STEPS: int = TURNS_PER_DAY * TOTAL_DAYS  # 720, confirmed exact

BOARD_SIZE: int = 10  # four 5x5 quadrants
STARTING_MONEY: int = 3_000
QUADRANT_COSTS: tuple[int, ...] = (1_000, 2_000, 4_000)  # cost of the 2nd/3rd/4th quadrant; NW starts unlocked
# Confirmed via a real observation: unlocked_quadrants is a list of these
# name strings (e.g. ["NW"]), not a count.
QUADRANT_NAMES: tuple[str, ...] = ("NW", "NE", "SW", "SE")

# NOT resolved: how many quadrants a strong agent should buy. The prior
# main.py/new_agent_wip.py comments disagreed with each other (one claims
# real top players stopped at exactly 3, a different comment justifies a
# coordinate-ascent-found cap of 2). Real 9-game data shows all 9 winners
# reached a 3rd quadrant by day 9-11 -- a point in favor of 3, but not a
# direct A/B test against 2. Keep this tunable, resolve via real self-play:
MAX_QUADRANTS_CANDIDATES: tuple[int, ...] = (2, 3)

# ---------------------------------------------------------------------------
# Action vocabulary — every other string is a confirmed silent no-op
# ---------------------------------------------------------------------------


class Action(str, Enum):
    NORTH = "NORTH"
    SOUTH = "SOUTH"
    EAST = "EAST"
    WEST = "WEST"
    PASS = "PASS"
    PICKUP = "PICKUP"
    DROP = "DROP"
    PLACE = "PLACE"
    PLANT = "PLANT"
    WATER = "WATER"
    HARVEST = "HARVEST"
    FERTILIZE = "FERTILIZE"
    FEED = "FEED"
    COLLECT_FERTILIZER = "COLLECT_FERTILIZER"
    CARE = "CARE"
    BUILD_COOP = "BUILD_COOP"
    BUILD_PASTURE = "BUILD_PASTURE"
    DIG = "DIG"  # confirmed weed-removal action
    BUY_SEED = "BUY_SEED"
    BUY_PRODUCT = "BUY_PRODUCT"  # wheat / fertilizer only
    BUY_ANIMAL = "BUY_ANIMAL"
    SELL = "SELL"
    HIRE = "HIRE"
    BUY_LAND = "BUY_LAND"
    # NOTE: SELL_ANIMAL, REMOVE_WEED, and ["PICKUP", "WEED"] are confirmed
    # to NOT exist. Any code path that still emits them is a silent no-op.


MAX_MARKET_ORDERS_PER_TURN: int = 10  # extras silently dropped

# ---------------------------------------------------------------------------
# Crop yield / decay — the single most important newly-confirmed mechanic.
# No prior agent version modeled this correctly; the shipped fix (bumping
# HARVEST's tier ahead of WATER) never used max_lifespan_step directly.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CropProfile:
    seed_cost: int
    base_price: int
    first_yield_day: int
    max_yield_day: int  # confirmed exact for all 5 crops, incl. ongoing ones
    max_yield: int  # fertilized max, per confirmed table
    max_yield_unfertilized: int | None = None
    ongoing_interval_days: int | None = None  # tomato=1, strawberry=2
    ongoing_productions: int | None = None  # both ongoing crops: 4


# Confirmed against README.md's Object Types table exactly.
CROPS: dict[str, CropProfile] = {
    "WHEAT": CropProfile(seed_cost=10, base_price=25, first_yield_day=2, max_yield_day=4, max_yield=6, max_yield_unfertilized=4),
    "CARROT": CropProfile(seed_cost=20, base_price=35, first_yield_day=2, max_yield_day=3, max_yield=4, max_yield_unfertilized=3),
    "MELON": CropProfile(seed_cost=80, base_price=250, first_yield_day=10, max_yield_day=10, max_yield=6),
    "TOMATO": CropProfile(seed_cost=50, base_price=60, first_yield_day=8, max_yield_day=11, max_yield=4, ongoing_interval_days=1, ongoing_productions=4),
    "STRAWBERRY": CropProfile(seed_cost=100, base_price=120, first_yield_day=10, max_yield_day=16, max_yield=4, ongoing_interval_days=2, ongoing_productions=4),
}


def is_decaying(max_lifespan_step: int, current_step: int) -> bool:
    """True once a tile has passed max_lifespan_step. -1 means "not
    applicable" (an ongoing crop, whose decay trigger isn't step-based) —
    treated as never-decaying here since that path isn't modeled yet."""
    if max_lifespan_step is None or max_lifespan_step < 0:
        return False
    return current_step > max_lifespan_step


def decay_urgency(max_lifespan_step: int, current_step: int) -> float:
    """Higher = more urgent to harvest NOW. Once decaying, yield_units drops
    by 1 every other turn until the tile becomes a weed — so every 2 turns
    of delay past max_lifespan_step is a full unit of yield, permanently
    lost. Ongoing crops (max_lifespan_step == -1) aren't modeled here yet —
    their decay trigger is a cumulative-production count, not a step
    number, and isn't derivable from a single observation."""
    if max_lifespan_step is None or max_lifespan_step < 0:
        return 0.0
    turns_past_decay = current_step - max_lifespan_step
    if turns_past_decay <= 0:
        return 0.0
    return turns_past_decay / 2.0


# ---------------------------------------------------------------------------
# Watering / feeding — miss 2 consecutive end-of-day refreshes = unrecoverable
# ---------------------------------------------------------------------------

MAX_CONSECUTIVE_UNWATERED: int = 2  # on the 2nd miss, tile becomes a weed
MAX_CONSECUTIVE_UNFED: int = 2  # on the 2nd miss, animal escapes
FRESH_PLANT_STARTING_UNWATERED: int = 1  # no grace period
FRESH_ANIMAL_STARTING_UNFED: int = 0  # one free day

# ---------------------------------------------------------------------------
# Shed
# ---------------------------------------------------------------------------

SHED_CAPACITY: int = 100  # flat cap; seeds live in a separate, uncapped slot
# Overflow at end-of-day drop is discarded, not held anywhere.

# ---------------------------------------------------------------------------
# Hiring
# ---------------------------------------------------------------------------


def hire_cost(hires_today: int) -> int:
    """Fibonacci cost, resets each day: 1, 1, 2, 3, 5, 8, 13, 21, ..."""
    a, b = 1, 1
    for _ in range(hires_today):
        a, b = b, a + b
    return a


# ---------------------------------------------------------------------------
# Town / shops — real per-shop demand table. Every prior agent used only a
# shop-count proxy; this table lets selling logic anticipate actual drains.
# ---------------------------------------------------------------------------

SHOPS: dict[str, tuple[str, ...]] = {
    "BAKERY": ("EGG", "WHEAT"),
    "PIZZA_SHOP": ("MILK", "TOMATO", "WHEAT"),
    "BRUNCH_SPOT": ("EGG", "WHEAT", "STRAWBERRY"),
    "YARN_STORE": ("WOOL",),  # single-product: 2x consumption
    "ICE_CREAM_SHOP": ("STRAWBERRY", "MILK", "WHEAT"),
    "PET_CAFE": ("CARROT",),  # single-product: 2x consumption
    "SMOOTHIE_SHOP": ("STRAWBERRY", "MILK"),
    "FARMERS_MARKET": ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY"),
}
SINGLE_PRODUCT_SHOPS: frozenset[str] = frozenset({"YARN_STORE", "PET_CAFE"})

TOWN_SHOP_SELL_INTERVAL: int = 4  # turns; each unlocked shop instance drains 1 of every listed product
TOWN_CENTER_SELL_INTERVAL: int = 24  # turns; drains 1 of every non-fertilizer product, flat rate
SHOP_UNLOCK_INTERVAL_DAYS: int = 3  # a new shop is drawn (with replacement) every 3 days
MAX_SHOP_INSTANCES: int = 8


def per_turn_shop_demand(unlocked_shops: list[str]) -> dict[str, float]:
    """Expected per-turn drain for each product from town/shop mechanics,
    given the current list of unlocked shop instances (duplicates allowed)."""
    demand: dict[str, float] = {}
    for shop in unlocked_shops:
        products = SHOPS.get(shop, ())
        weight = 2.0 if shop in SINGLE_PRODUCT_SHOPS else 1.0
        for product in products:
            demand[product] = demand.get(product, 0.0) + weight / TOWN_SHOP_SELL_INTERVAL
    return demand


# ---------------------------------------------------------------------------
# Market pricing — shape differs per resource. Exact amp/curve constants
# weren't captured in the source report, so this is directional only:
# melon/wool ("sq"): crash hard on gluts, sell early and steadily.
# wheat ("log"): forgiving on gluts, safe to sell in bulk.
# carrot/tomato/egg ("hinge"): stays near base until a scarcity knee, then
#   rises fast — avoid dumping inventory that resets this knee.
# ---------------------------------------------------------------------------

MARKET_STARTING_INVENTORY: int = 10_000  # I0, every product

# -------- from state.py --------
"""
state.py — Clean, typed representations of parsed Kaggriculture observations.

Rewritten against the official AGENTS.md / README.md shipped inside the
installed kaggle_environments package — not guessed, not reconstructed
from an agent file's comments. Every field name and shape here is a
direct match to the documented Observation Format.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class TileState:
    x: int
    y: int
    locked: bool = False
    kind: str | None = None  # "PLANT" | "WEED" | "COOP" | "PASTURE" | None (empty, unlocked)

    # PLANT fields
    crop: str | None = None
    planted_day: int | None = None
    watered_today: bool = False
    consecutive_unwatered: int = 0
    yield_units: int = 0
    max_lifespan_step: int = -1  # -1 = not applicable (ongoing crop, or non-plant tile)
    fertilized_until_day: int = -1  # -1 = no active fertilizer bonus

    # COOP / PASTURE fields
    animal: str | None = None
    placed_day: int | None = None
    fed_today: bool = False
    consecutive_unfed: int = 0
    cared_today: bool = False
    fertilizer_available: bool = False
    pending_care_bonus: int = 0

    def is_fertilized(self, current_day: int) -> bool:
        return self.fertilized_until_day >= current_day

    @classmethod
    def from_raw(cls, x: int, y: int, raw_cell: Any) -> "TileState":
        if raw_cell is None:
            return cls(x=x, y=y)
        if raw_cell == "LOCKED":
            return cls(x=x, y=y, locked=True)
        if not isinstance(raw_cell, dict):
            # Unrecognized shape -- treat as empty rather than crash.
            return cls(x=x, y=y)

        kind = raw_cell.get("kind")
        if kind == "PLANT":
            return cls(
                x=x, y=y, kind="PLANT",
                crop=raw_cell.get("crop"),
                planted_day=raw_cell.get("planted_day"),
                watered_today=raw_cell.get("watered_today", False),
                consecutive_unwatered=raw_cell.get("consecutive_unwatered", 0),
                yield_units=raw_cell.get("yield_units", 0),
                max_lifespan_step=raw_cell.get("max_lifespan_step", -1),
                fertilized_until_day=raw_cell.get("fertilized_until_day", -1),
            )
        if kind == "WEED":
            return cls(x=x, y=y, kind="WEED")
        if kind in ("COOP", "PASTURE"):
            return cls(
                x=x, y=y, kind=kind,
                animal=raw_cell.get("animal"),
                placed_day=raw_cell.get("placed_day"),
                yield_units=raw_cell.get("yield_units", 0),
                fed_today=raw_cell.get("fed_today", False),
                consecutive_unfed=raw_cell.get("consecutive_unfed", 0),
                cared_today=raw_cell.get("cared_today", False),
                fertilizer_available=raw_cell.get("fertilizer_available", False),
                pending_care_bonus=raw_cell.get("pending_care_bonus", 0),
            )
        return cls(x=x, y=y)  # unrecognized "kind" -- treat as empty


@dataclass
class UnitState:
    unit_id: str  # "farmer" or "hand_0", "hand_1", ... -- local bookkeeping
    # only; never sent back in the action (the real action addresses the
    # farmer and hands by their fixed "farmer"/"hands" keys, not by id).
    x: int
    y: int
    carrying: dict[str, int] = field(default_factory=dict)


@dataclass
class FarmState:
    step: int
    day: int
    hour: int
    money: float
    shed: dict[str, int]
    seeds: dict[str, int]
    market_prices: dict[str, float]
    market_inventory: dict[str, int]
    unlocked_shops: list[str]
    unlocked_quadrants: list[str]  # e.g. ["NW"] -- names, not a count
    hires_today: int
    tiles: list[TileState]
    farmer: UnitState
    hands: list[UnitState]


def size_keeper_pool(n_units: int, n_animals_active: int) -> int:
    """
    Independently verified stable-pool-sizing formula. Sizing off herd size
    rather than raw unit count keeps pool membership stable across a
    same-day hire. Kept ready for when hiring is implemented and n_units
    actually grows past 1.
    """
    return max(1, min(3, n_units - 2, 1 + n_animals_active // 3))

# -------- from strategy.py --------
"""
strategy.py — Task generation and prioritization.

Rewritten against the official tile schema (kind-discriminated: "PLANT",
"WEED", "COOP", "PASTURE", or empty). HARVEST priority is driven directly
by max_lifespan_step (decay) for one-time crops -- the single biggest gap
in every prior version of this project.

Known gaps, intentionally not solved here:
- Ongoing-crop (tomato/strawberry) decay isn't modeled: their
  max_lifespan_step is always -1 (the engine tracks their decay trigger
  by cumulative production count, not a step number), and that count
  isn't derivable from a single observation.
- Crop selection for empty tiles is a placeholder (always WHEAT).
- Only the main farmer is assigned a task; hands (once hiring is
  implemented) aren't scheduled yet.
"""

from dataclasses import dataclass



@dataclass
class Task:
    kind: str
    tile: TileState
    urgency: float  # higher = more urgent; used to sort, not a fixed tier


BASE_URGENCY: dict[str, float] = {
    "FEED_CRITICAL": 100.0,
    "WATER_CRITICAL": 95.0,
    "HARVEST_DECAYING": 90.0,
    "PLACE": 80.0,
    "FEED_ROUTINE": 60.0,
    "WATER_ROUTINE": 55.0,
    "HARVEST_FRESH": 50.0,
    "CARE": 45.0,
    "DIG": 40.0,
    "BUILD": 35.0,
    "PLANT": 30.0,
    "FERTILIZE": 20.0,
    "COLLECT_FERTILIZER": 10.0,
}


def harvest_urgency(tile: TileState, current_step: int) -> float:
    """Decay-aware HARVEST urgency for a PLANT tile. Reads
    max_lifespan_step directly rather than inferring decay."""
    urgency = decay_urgency(tile.max_lifespan_step, current_step)
    if urgency > 0:
        return BASE_URGENCY["HARVEST_DECAYING"] + min(urgency, 10.0) * max(tile.yield_units, 1)
    if tile.yield_units > 0:
        return BASE_URGENCY["HARVEST_FRESH"]
    return 0.0


def generate_tasks(farm: FarmState) -> list[Task]:
    tasks: list[Task] = []

    for tile in farm.tiles:
        if tile.locked:
            continue  # every tile action no-ops on an unbought quadrant

        if tile.kind == "WEED":
            tasks.append(Task("DIG", tile, BASE_URGENCY["DIG"]))
            continue

        if tile.kind == "PLANT":
            u = harvest_urgency(tile, farm.step)
            if u > 0:
                tasks.append(Task("HARVEST", tile, u))
            if not tile.watered_today:
                grace_left = MAX_CONSECUTIVE_UNWATERED - tile.consecutive_unwatered
                key = "WATER_CRITICAL" if grace_left <= 1 else "WATER_ROUTINE"
                tasks.append(Task("WATER", tile, BASE_URGENCY[key]))
            if not tile.is_fertilized(farm.day):
                tasks.append(Task("FERTILIZE", tile, BASE_URGENCY["FERTILIZE"]))
            continue

        if tile.kind in ("COOP", "PASTURE"):
            if tile.animal is None:
                tasks.append(Task("PLACE", tile, BASE_URGENCY["PLACE"]))
            else:
                if tile.yield_units > 0:
                    tasks.append(Task("HARVEST", tile, BASE_URGENCY["HARVEST_FRESH"]))
                if not tile.fed_today:
                    grace_left = MAX_CONSECUTIVE_UNFED - tile.consecutive_unfed
                    key = "FEED_CRITICAL" if grace_left <= 1 else "FEED_ROUTINE"
                    tasks.append(Task("FEED", tile, BASE_URGENCY[key]))
                if not tile.cared_today:
                    tasks.append(Task("CARE", tile, BASE_URGENCY["CARE"]))
                if tile.fertilizer_available:
                    tasks.append(Task("COLLECT_FERTILIZER", tile, BASE_URGENCY["COLLECT_FERTILIZER"]))
            continue

        # tile.kind is None -- empty, unlocked, plantable
        tasks.append(Task("PLANT", tile, BASE_URGENCY["PLANT"]))

    tasks.sort(key=lambda t: t.urgency, reverse=True)
    return tasks


def shop_aware_sell_plan(farm: FarmState, max_orders: int = 8) -> list[tuple[str, int]]:
    """
    Sell whatever's in the shed. Unsold inventory earns nothing (the
    confirmed reward rule: "unsold items in inventory do not count"), so
    there's no reason to hold produce back at this scale.

    This replaces an earlier version that only sold once the shed was
    nearly full -- a reasonable-sounding "don't let it overflow"
    heuristic that was actually the reason a real test run showed money
    going steadily DOWN over 720 turns: with one or two crop tiles, the
    shed never gets anywhere near full, so that version silently never
    sold anything while still spending on seeds. Matches the pattern in
    AGENTS.md's own reference agent instead (sell unconditionally, no
    threshold). mechanics.py::per_turn_shop_demand is still there for a
    later pass that times sales around passive town demand -- not used
    to gate selling for now.
    """
    plan: list[tuple[str, int]] = [(item, qty) for item, qty in farm.shed.items() if qty > 0]
    plan.sort(key=lambda p: p[1], reverse=True)
    return plan[:max_orders]

# -------- from agent.py --------
"""
agent.py — Kaggriculture submission entrypoint.

Rewritten against the official AGENTS.md / README.md shipped inside the
installed kaggle_environments package. Both the observation shape and the
action format below are direct matches to that documentation, not guesses:

    return {
        "farmer": [op, ...args],
        "hands":  [[op, ...args], ...],   # one per hired hand, in order
        "market": [[op, ...args], ...],
    }

This is the fix for the earlier version, which returned a bare list
(["WEST"]) — silently wrong, since the engine expects this dict shape.
That's almost certainly why reward stayed pinned at exactly $3000 even
once the observation parsing itself was corrected.
"""

import logging
from typing import Any


logger = logging.getLogger("kaggriculture_agent")
logging.basicConfig(level=logging.WARNING)

# Placeholder crop-selection heuristic -- always WHEAT. CROPS in
# mechanics.py has profiles for CARROT/TOMATO/STRAWBERRY/MELON too; a real
# selection heuristic (season timing, market price, land-use mix) is the
# next piece of strategy to build, not this pass.
DEFAULT_PLANT_CROP = "WHEAT"


def parse_observation(obs: dict[str, Any], config: dict[str, Any]) -> FarmState:
    player_idx = obs["player"]
    my_farm = obs["farms"][player_idx]
    private = obs["private"]
    market = obs["market"]
    town = obs["town"]

    tiles: list[TileState] = [
        TileState.from_raw(x, y, cell)
        for y, row in enumerate(my_farm["tiles"])
        for x, cell in enumerate(row)
    ]

    # private["inventories"][0] is the main farmer; [1:] are hands, in the
    # same order as farm["hands"].
    raw_inventories = private.get("inventories", [])

    fx, fy = my_farm["farmer"]
    farmer = UnitState(
        unit_id="farmer",
        x=fx,
        y=fy,
        carrying=raw_inventories[0] if raw_inventories else {},
    )

    hands: list[UnitState] = []
    for i, (hx, hy) in enumerate(my_farm.get("hands", [])):
        carrying = raw_inventories[i + 1] if i + 1 < len(raw_inventories) else {}
        hands.append(UnitState(unit_id=f"hand_{i}", x=hx, y=hy, carrying=carrying))

    return FarmState(
        step=obs.get("step", 0),
        day=obs.get("day", 0),
        hour=obs.get("hour", 0),
        money=my_farm.get("money", 0.0),
        shed=private.get("shed", {}),
        seeds=private.get("seeds", {}),
        market_prices=market.get("prices", {}),
        market_inventory=market.get("inventory", {}),
        unlocked_shops=town.get("unlocked_shops", []),
        unlocked_quadrants=my_farm.get("unlocked_quadrants", []),
        hires_today=my_farm.get("hires_today", 0),
        tiles=tiles,
        farmer=farmer,
        hands=hands,
    )


def _direction_toward(from_x: int, from_y: int, to_x: int, to_y: int) -> str | None:
    """Greedy straight-line stepping -- locked tiles are confirmed
    passable, so no pathfinding/obstacle-avoidance is needed."""
    dx = to_x - from_x
    dy = to_y - from_y
    if dx == 0 and dy == 0:
        return None
    if abs(dx) >= abs(dy):
        return "EAST" if dx > 0 else "WEST"
    return "SOUTH" if dy > 0 else "NORTH"


def _farmer_op(farm: FarmState, market_orders: list[Any]) -> list[Any]:
    """Decide the main farmer's single op this turn. May append a market
    order it depends on (buying a seed before it can plant)."""
    tasks = generate_tasks(farm)
    if not tasks:
        return ["PASS"]

    task = tasks[0]  # highest urgency

    if task.kind == "PLANT" and farm.seeds.get(DEFAULT_PLANT_CROP, 0) <= 0:
        cost = CROPS[DEFAULT_PLANT_CROP].seed_cost
        if farm.money >= cost:
            market_orders.append(["BUY_SEED", DEFAULT_PLANT_CROP, 1])
        # keep walking toward the tile in the meantime -- no reason to
        # idle while the seed purchase is in flight

    direction = _direction_toward(farm.farmer.x, farm.farmer.y, task.tile.x, task.tile.y)
    if direction is not None:
        return [direction]

    if task.kind == "PLANT":
        if farm.seeds.get(DEFAULT_PLANT_CROP, 0) <= 0:
            return ["PASS"]  # on the tile, but the seed hasn't landed yet
        return ["PLANT", DEFAULT_PLANT_CROP]

    return [task.kind]


def agent(obs: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    try:
        farm = parse_observation(obs, config)
    except Exception:
        logger.exception("parse_observation failed; passing this turn as a safe fallback")
        return {"farmer": ["PASS"], "hands": [], "market": []}

    market_orders: list[Any] = []
    farmer_op = _farmer_op(farm, market_orders)

    for item, qty in shop_aware_sell_plan(farm):
        market_orders.append(["SELL", item, qty])

    # Hands aren't hired in this pass, so there's nothing to control yet --
    # HIRE and per-hand task assignment are the next real piece of work.
    hand_ops: list[Any] = []

    return {"farmer": farmer_op, "hands": hand_ops, "market": market_orders}

