"""
build_submission.py — Concatenates the modular src/kaggriculture/ files into
one self-contained file for Kaggle submission.

Why this exists: Kaggle simulation competitions (this one included, since
it's built on kaggle_environments) load the submitted agent file in
isolation at grading time — your repo's other files are not present. A
`from state import ...`-style import that works fine locally or in a
notebook will raise ModuleNotFoundError on the real submission. This
script produces the flattened single-file version so you never have to
hand-merge changes before submitting.

Usage:
    python scripts/build_submission.py
    # writes submission/main.py — commit this file; re-run after any
    # change under src/kaggriculture/ and commit the updated output too.
"""

from __future__ import annotations
import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src" / "kaggriculture"
OUT_PATH = REPO_ROOT / "submission" / "main.py"

# Dependency order matters: each file may use names defined in an earlier
# one, so later files must be concatenated after their dependencies.
ORDER = ["mechanics.py", "state.py", "strategy.py", "agent.py"]

_MODULE_NAMES = "|".join(name.removesuffix(".py") for name in ORDER)
# Matches a local intra-package import, single-line or parenthesized
# multi-line, e.g.:
#   from mechanics import Action
#   from state import (
#       FarmState,
#       TileState,
#   )
# These become unnecessary once everything lands in one file, so they're
# stripped entirely rather than left dangling.
LOCAL_IMPORT_RE = re.compile(
    rf"^from (?:{_MODULE_NAMES}) import (?:\([^)]*\)|[^\n]*)\n?",
    re.MULTILINE,
)

# Every source file starts with `from __future__ import annotations` for
# its own standalone type hints. That's only legal once per file, at the
# very top — concatenating four copies is a SyntaxError (caught by
# verify() the first time this ran). Stripped per-file; added back exactly
# once in the generated header instead.
FUTURE_IMPORT_RE = re.compile(r"^from __future__ import .*\n?", re.MULTILINE)


def build() -> Path:
    OUT_PATH.parent.mkdir(exist_ok=True)

    header = [
        "# AUTO-GENERATED by scripts/build_submission.py — do not hand-edit.",
        "# Source of truth is src/kaggriculture/. Edit there, then re-run:",
        "#     python scripts/build_submission.py",
        "from __future__ import annotations",
        "",
    ]
    parts: list[str] = list(header)

    for filename in ORDER:
        file_path = SRC / filename
        if not file_path.exists():
            raise FileNotFoundError(f"Expected source file missing: {file_path}")
        text = file_path.read_text()
        text = LOCAL_IMPORT_RE.sub("", text)
        text = FUTURE_IMPORT_RE.sub("", text)
        parts.append(f"# {'-' * 8} from {filename} {'-' * 8}")
        parts.append(text.strip())
        parts.append("")

    OUT_PATH.write_text("\n".join(parts) + "\n")
    return OUT_PATH


def verify(path: Path) -> None:
    """Byte-compile the generated file to catch obvious breakage (a
    stripped import that was actually needed, a duplicate definition)
    before it gets committed as the submission."""
    result = subprocess.run(
        ["python3", "-m", "py_compile", str(path)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise SystemExit(
            f"Generated file failed to compile:\n{result.stderr}\n"
            "Fix src/kaggriculture/ and re-run the build."
        )


if __name__ == "__main__":
    output = build()
    verify(output)
    print(f"Wrote {output}")
    print("Compiles clean. Commit this file alongside your src/ change.")
